/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-123549-g70537ec8e6-20260318"
#endif /* AVUTIL_FFVERSION_H */
